### ISSUE TITLE
Feedback/peer review

### ISSUE THREAD

**Issue by RebeccaFransson** [JuliaSivartsson/laboration1-ruby-1dv450#1]
Din applikation ser awesome ut! Synd att du hade lite problem med heroku. Jag använde mig också utav det men följde deras guide på hemsidan och "railstutorial" boken, det hjälpte mig! Det visade sig att jag skulle använda mig utav puma-server och några andra gems i development-mode.

Din applikation mäter upp till kraven för labortaion 1. 
När du genererar ut din api nyckel tilldelar du nycklen till applikationen efter du sparat. Jag har ingen aning om det är bättre eller sämre än att göra det före du skallar på save. Men jag gjorde så här:
`@app = App.new(app_params)`
`@app.key = [*('a'..'z'),*('0'..'9')].shuffle[0,50].join`
Min kod för att skapa en nyckel tror jag går snabbare än din loop dock. Men nu har du iallafall ett till vis detta går att skriva på! :)

Jag undrar också varför du har delete_application i sessions-kontrollern, har inte det med appen att göra och borde ligga i app-kontrollern?

Ett tips är också att återkommande variabler i vyn kan man göra tillgängliga för alla vyer med hjälp utav att skriva en `helper_method` i application-kontrollern. Till exempel gjorde jag detta med min variabel för den inloggade användaren som jag döpte till `:current_user`. Och när jag skapade `:current_user` i application-kontrollern såg jag till att bara skapa den en gång, så nästa gång jag kallar på `:current_user` så slipper systemet ställa en "find"-fråga till databasen igen.
Skrivs på detta sättet: `@current ||= User.find(session[:userId]) if session[:userId]`

Jag hoppas jag gav några bra tips och att jag fattat denna peer-review-uppgiften rätt! :) Lycka till!

**Comment by 1dv450** [comment]
Bra kommentarer och feedback!
